/* This file was automatically generated by:
 * `create_driver_header_file_list` method of
 * `create_peripheral_device_drivers.py`
 */

#ifndef H_IOB_UART16550_DRIVER_FILES_H
#define H_IOB_UART16550_DRIVER_FILES_H

/** @file
 *  @brief iob_uart16550 driver file paths.
 */

#define IOB_UART16550_DRIVER_NAME "iob_uart16550"      /**< Driver name. */
#define IOB_UART16550_DRIVER_CLASS "iob_uart16550"     /**< Driver class. */
#define IOB_UART16550_DEVICE_FILE "/dev/iob_uart16550" /**< Device file path.  \
                                                        */
#define IOB_UART16550_DEVICE_CLASS                                             \
  "/sys/class/" IOB_UART16550_DRIVER_CLASS                                     \
  "/" IOB_UART16550_DRIVER_NAME /**< Device class path. */

/**
 * @brief System file paths for CSRs.
 */
#define IOB_UART16550_SYSFILE_RBR_THR_DLL                                      \
  IOB_UART16550_DEVICE_CLASS                                                   \
      "/rbr_thr_dll" /**< System file path for rbr_thr_dll CSR. */
#define IOB_UART16550_SYSFILE_IER_DLM                                          \
  IOB_UART16550_DEVICE_CLASS                                                   \
      "/ier_dlm" /**< System file path for ier_dlm CSR. */
#define IOB_UART16550_SYSFILE_IIR_FCR                                          \
  IOB_UART16550_DEVICE_CLASS                                                   \
      "/iir_fcr" /**< System file path for iir_fcr CSR. */
#define IOB_UART16550_SYSFILE_LCR                                              \
  IOB_UART16550_DEVICE_CLASS "/lcr" /**< System file path for lcr CSR. */
#define IOB_UART16550_SYSFILE_MCR                                              \
  IOB_UART16550_DEVICE_CLASS "/mcr" /**< System file path for mcr CSR. */
#define IOB_UART16550_SYSFILE_LSR                                              \
  IOB_UART16550_DEVICE_CLASS "/lsr" /**< System file path for lsr CSR. */
#define IOB_UART16550_SYSFILE_MSR                                              \
  IOB_UART16550_DEVICE_CLASS "/msr" /**< System file path for msr CSR. */
#define IOB_UART16550_SYSFILE_VERSION                                          \
  IOB_UART16550_DEVICE_CLASS                                                   \
      "/version" /**< System file path for version CSR. */

#include "iob_uart16550_csrs_conf.h"

#endif // H_IOB_UART16550_DRIVER_FILES_H
