/* This file was automatically generated by:
 * `create_sysfs_driver_header_file` method of
 * `create_peripheral_device_drivers.py`
 */

#ifndef H_IOB_UART16550_SYSFS_H
#define H_IOB_UART16550_SYSFS_H

// Sysfs show/store functions
static ssize_t sysfs_enosys_show(struct device *dev,
                                 struct device_attribute *attr, char *buf) {
  return -ENOSYS;
}

static ssize_t sysfs_enosys_store(struct device *dev,
                                  struct device_attribute *attr,
                                  const char *buf, size_t count) {
  return -ENOSYS;
}

static ssize_t sysfs_rbr_thr_dll_store(struct device *dev,
                                       struct device_attribute *attr,
                                       const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_uart16550_mutex)) {
    pr_info("[iob_uart16550] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_uart16550_mutex);
    return ret;
  }
  iob_data_write_reg(iob_uart16550_data.regbase, value,
                     IOB_UART16550_CSRS_RBR_THR_DLL_ADDR,
                     IOB_UART16550_CSRS_RBR_THR_DLL_W);
  mutex_unlock(&iob_uart16550_mutex);
  pr_info("[iob_uart16550] Sysfs - Write rbr_thr_dll: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_ier_dlm_store(struct device *dev,
                                   struct device_attribute *attr,
                                   const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_uart16550_mutex)) {
    pr_info("[iob_uart16550] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_uart16550_mutex);
    return ret;
  }
  iob_data_write_reg(iob_uart16550_data.regbase, value,
                     IOB_UART16550_CSRS_IER_DLM_ADDR,
                     IOB_UART16550_CSRS_IER_DLM_W);
  mutex_unlock(&iob_uart16550_mutex);
  pr_info("[iob_uart16550] Sysfs - Write ier_dlm: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_iir_fcr_store(struct device *dev,
                                   struct device_attribute *attr,
                                   const char *buf, size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_uart16550_mutex)) {
    pr_info("[iob_uart16550] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_uart16550_mutex);
    return ret;
  }
  iob_data_write_reg(iob_uart16550_data.regbase, value,
                     IOB_UART16550_CSRS_IIR_FCR_ADDR,
                     IOB_UART16550_CSRS_IIR_FCR_W);
  mutex_unlock(&iob_uart16550_mutex);
  pr_info("[iob_uart16550] Sysfs - Write iir_fcr: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_lcr_store(struct device *dev,
                               struct device_attribute *attr, const char *buf,
                               size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_uart16550_mutex)) {
    pr_info("[iob_uart16550] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_uart16550_mutex);
    return ret;
  }
  iob_data_write_reg(iob_uart16550_data.regbase, value,
                     IOB_UART16550_CSRS_LCR_ADDR, IOB_UART16550_CSRS_LCR_W);
  mutex_unlock(&iob_uart16550_mutex);
  pr_info("[iob_uart16550] Sysfs - Write lcr: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_mcr_store(struct device *dev,
                               struct device_attribute *attr, const char *buf,
                               size_t count) {
  u32 value = 0;
  int ret;
  if (!mutex_trylock(&iob_uart16550_mutex)) {
    pr_info("[iob_uart16550] Another process is accessing the device\n");
    return -EBUSY;
  }
  ret = kstrtouint(buf, 0, &value);
  if (ret) {
    mutex_unlock(&iob_uart16550_mutex);
    return ret;
  }
  iob_data_write_reg(iob_uart16550_data.regbase, value,
                     IOB_UART16550_CSRS_MCR_ADDR, IOB_UART16550_CSRS_MCR_W);
  mutex_unlock(&iob_uart16550_mutex);
  pr_info("[iob_uart16550] Sysfs - Write mcr: 0x%x\n", value);
  return count;
}

static ssize_t sysfs_lsr_show(struct device *dev, struct device_attribute *attr,
                              char *buf) {
  u32 value =
      iob_data_read_reg(iob_uart16550_data.regbase, IOB_UART16550_CSRS_LSR_ADDR,
                        IOB_UART16550_CSRS_LSR_W);
  pr_info("[iob_uart16550] Sysfs - Read lsr: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_msr_show(struct device *dev, struct device_attribute *attr,
                              char *buf) {
  u32 value =
      iob_data_read_reg(iob_uart16550_data.regbase, IOB_UART16550_CSRS_MSR_ADDR,
                        IOB_UART16550_CSRS_MSR_W);
  pr_info("[iob_uart16550] Sysfs - Read msr: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

static ssize_t sysfs_version_show(struct device *dev,
                                  struct device_attribute *attr, char *buf) {
  u32 value = iob_data_read_reg(iob_uart16550_data.regbase,
                                IOB_UART16550_CSRS_VERSION_ADDR,
                                IOB_UART16550_CSRS_VERSION_W);
  pr_info("[iob_uart16550] Sysfs - Read version: 0x%x\n", value);
  return sprintf(buf, "%u", value);
}

// Device attributes
DEVICE_ATTR(rbr_thr_dll, 0600, sysfs_rbr_thr_dll_show, sysfs_rbr_thr_dll_store);
DEVICE_ATTR(ier_dlm, 0600, sysfs_ier_dlm_show, sysfs_ier_dlm_store);
DEVICE_ATTR(iir_fcr, 0600, sysfs_iir_fcr_show, sysfs_iir_fcr_store);
DEVICE_ATTR(lcr, 0600, sysfs_lcr_show, sysfs_lcr_store);
DEVICE_ATTR(mcr, 0200, sysfs_enosys_show, sysfs_mcr_store);
DEVICE_ATTR(lsr, 0400, sysfs_lsr_show, sysfs_enosys_store);
DEVICE_ATTR(msr, 0400, sysfs_msr_show, sysfs_enosys_store);
DEVICE_ATTR(version, 0400, sysfs_version_show, sysfs_enosys_store);

// Probe / Remove functions
static int iob_uart16550_create_device_attr_files(struct device *device) {
  int ret = 0;
  ret |= device_create_file(device, &dev_attr_rbr_thr_dll);
  ret |= device_create_file(device, &dev_attr_ier_dlm);
  ret |= device_create_file(device, &dev_attr_iir_fcr);
  ret |= device_create_file(device, &dev_attr_lcr);
  ret |= device_create_file(device, &dev_attr_mcr);
  ret |= device_create_file(device, &dev_attr_lsr);
  ret |= device_create_file(device, &dev_attr_msr);
  ret |= device_create_file(device, &dev_attr_version);
  return ret;
}

static void
iob_uart16550_remove_device_attr_files(struct iob_data *iob_uart16550_data) {
  device_remove_file(iob_uart16550_data->device, &dev_attr_rbr_thr_dll);
  device_remove_file(iob_uart16550_data->device, &dev_attr_ier_dlm);
  device_remove_file(iob_uart16550_data->device, &dev_attr_iir_fcr);
  device_remove_file(iob_uart16550_data->device, &dev_attr_lcr);
  device_remove_file(iob_uart16550_data->device, &dev_attr_mcr);
  device_remove_file(iob_uart16550_data->device, &dev_attr_lsr);
  device_remove_file(iob_uart16550_data->device, &dev_attr_msr);
  device_remove_file(iob_uart16550_data->device, &dev_attr_version);
  device_destroy(iob_uart16550_data->class, iob_uart16550_data->devnum);
  return;
}

#endif // H_IOB_UART16550_SYSFS_H
